import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <TRPCReactProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          {children}
          <Toaster />
        </body>
      </html>
    </TRPCReactProvider>
  )
}